language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - nightly
notifications:
  email: false
after_script:
    - julia -e 'cd(Pkg.dir("IterTools")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
